#!/bin/bash

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
SQUID_STATUS=`/sbin/e-smith/config getprop squid status`

if systemctl is-active squid; then
  systemctl stop squid
fi

# Remove old squid SSL Database
rm -Rf /var/lib/ssl_db

# Reinitialize ssl_db
/usr/lib64/squid/ssl_crtd -c -s /var/lib/ssl_db

# Remove old squid cache
rm -Rf /var/spool/squid

# Reinitialize squid cache
if [ "$SQUID_STATUS" = "enabled" ]; then
  squid -z -F -N
  systemctl start squid
fi


exit 0
